import type { JellyId } from '../levels/jellies';
import type { GuideEntry } from './types';

/**
 * Fact cards for the jellyfish, one species per zone. Figures are approximate
 * adult maximums from SeaLifeBase, MarLIN, MBARI, NOAA Ocean Exploration,
 * Monterey Bay Aquarium and published papers. Jelly weights are rarely
 * recorded, so cards say so rather than guess.
 */
export const JELLY_GUIDE = {
  moonjelly: {
    latin: 'Aurelia aurita',
    length: 'bell usually 25-40 cm; fringe of short tentacles',
    weight: 'not recorded; ~95% water',
    lifespan: 'medusa up to ~1-2 years; polyps live on for years',
    speed: 'slow, steady pulsing; mostly drifts',
    depth: '0-1,250 m recorded, mostly near the coastal surface',
    range: 'NE Atlantic; lookalike Aurelia species worldwide',
    eats: 'plankton, fish eggs and larvae',
    fact: 'Each polyp buds off a stack of baby jellies that peel away one by one like saucers.',
  },
  compassjelly: {
    latin: 'Chrysaora hysoscella',
    length: 'bell up to ~30 cm; 24 tentacles, 4 long arms',
    weight: 'not recorded; mostly water',
    lifespan: 'medusa lives one season, spring to autumn',
    speed: 'slow pulsing; drifts with the currents',
    depth: '0-500 m, mostly above 150 m',
    range: 'NE Atlantic and Mediterranean',
    eats: 'plankton, fish larvae, other jellies',
    fact: 'It starts out male and turns female as it grows.',
  },
  seanettle: {
    latin: 'Chrysaora fuscescens',
    length: 'bell up to ~45 cm; arms up to ~4.5 m',
    weight: 'not recorded; mostly water',
    lifespan: 'medusa months; not well known in the wild',
    speed: 'steady pulsing; drifts in coastal currents',
    depth: 'coastal surface waters; exact range not well recorded',
    range: 'NE Pacific, Alaska to Mexico',
    eats: 'plankton, fish eggs and larvae, other jellies',
    fact: 'Baby crabs ride on its bell and arms, stealing its food and nibbling the jelly.',
  },
  // Representative: the Australian box jellyfish, the best-studied box jelly.
  boxjelly: {
    latin: 'Chironex fleckeri',
    length: 'bell up to ~30 cm; tentacles up to ~3 m',
    weight: 'up to ~2 kg',
    lifespan: 'medusa lives one wet season, a few months',
    speed: 'jet-swims; often quoted up to ~4 knots',
    depth: 'shallow coasts, mostly under 5 m',
    range: 'N Australia and nearby Indo-West Pacific',
    eats: 'prawns, small fish',
    fact: 'It has 24 eyes, 8 of them with lenses, and steers around obstacles.',
  },
  lionsmane: {
    latin: 'Cyanea capillata',
    length: 'bell up to ~2 m; tentacles up to ~36 m',
    weight: 'not reliably recorded',
    lifespan: 'medusa about one year; polyps live longer',
    speed: 'slow pulsing; drifts with the currents',
    depth: '0-85 m, mostly near the surface',
    range: 'cold Arctic, N Atlantic and N Pacific waters',
    eats: 'plankton, small fish, other jellies',
    fact: 'One found in 1870 trailed ~36 m of tentacles, longer than a blue whale.',
  },
  mauvestinger: {
    latin: 'Pelagia noctiluca',
    length: 'bell up to ~12 cm; 8 long tentacles',
    weight: 'not recorded; mostly water',
    lifespan: 'medusa ~2-6 months; it has no polyp stage',
    speed: 'pulses; rises to the surface at night',
    depth: 'mostly 0-150 m; recorded to ~1,400 m',
    range: 'warm and temperate seas worldwide',
    eats: 'plankton, fish eggs and larvae, other jellies',
    fact: 'Its name means "night light": touched, it glows and can leave a glowing slime.',
  },
  // Representative: a lobate comb jelly of the twilight zone.
  combjelly: {
    latin: 'Bathocyroe fosteri',
    length: '~2-4 cm across its lobes',
    weight: 'not recorded; mostly water',
    lifespan: 'unknown',
    speed: 'hangs still; rows on 8 comb rows, flaps lobes',
    depth: '200-1,000 m',
    range: 'all the world\'s oceans',
    eats: 'copepods, amphipods, krill',
    fact: 'Not a true jellyfish: it rows with combs of hairs that flash rainbows, and glows when touched.',
  },
  atolla: {
    latin: 'Atolla wyvillei',
    length: 'bell up to ~17 cm; ~20 tentacles plus one long one',
    weight: 'not recorded',
    lifespan: 'unknown',
    speed: 'slow pulsing; drifts trailing one long tentacle',
    depth: '~500-4,000 m, mostly 600-1,500 m',
    range: 'deep oceans worldwide',
    eats: 'small crustaceans, other drifting animals',
    fact: 'Attacked, it flashes rings of blue light, a burglar alarm calling bigger hunters to its attacker.',
  },
  crownjelly: {
    latin: 'Periphylla periphylla',
    length: 'bell up to ~35 cm tall; 12 thick tentacles',
    weight: 'not well recorded; ~0.5 kg on average',
    lifespan: 'possibly decades; matures at ~3-4 years',
    speed: 'slow pulsing; sinks away from light',
    depth: '0-2,900 m, mostly below 300 m by day',
    range: 'deep oceans worldwide; Norwegian fjords',
    eats: 'copepods, krill, amphipods, sea snails',
    fact: 'Light can harm it, so it stays deep by day and rises only in the dark of night.',
  },
  // Representative: the genus Crossota, the deepest jellyfish on record.
  trenchjelly: {
    latin: 'Crossota sp.',
    length: 'bell up to ~4 cm; ~200 fine tentacles',
    weight: 'not recorded; tiny and watery',
    lifespan: 'unknown; no polyp stage',
    speed: 'hangs still, tentacles spread; pulses slowly',
    depth: 'deep sea; filmed down to 9,066 m',
    range: 'deep oceans; filmed in the Mariana Trench',
    eats: 'likely copepods and other tiny drifters',
    fact: 'Filmed at 9,066 m in the Mariana Trench, it is the deepest jellyfish ever recorded.',
  },
} as const satisfies Record<JellyId, GuideEntry>;
