import type { GuideEntry } from './types';

/**
 * Fact cards for the seabed crawlers, the birds and the fish you swim as.
 * Figures are approximate adult maximums from FishBase, SeaLifeBase, MarLIN,
 * BTO ringing records and similar references.
 */
export const OTHER_GUIDE = {
  // Representative: the European green (shore) crab.
  shorecrab: {
    latin: 'Carcinus maenas',
    length: 'shell up to ~8 cm wide',
    weight: 'not well recorded; a palm-sized crab',
    lifespan: 'up to ~7 years',
    speed: 'scuttles sideways, fast in short bursts',
    depth: '0-60 m, mostly between the tides',
    range: 'NE Atlantic; invasive on many other coasts',
    eats: 'mussels, snails, worms, small crabs, algae',
    fact: 'It is listed among the 100 worst invasive species on Earth.',
  },
  // Representative: the common periwinkle.
  periwinkle: {
    latin: 'Littorina littorea',
    length: 'shell up to ~5 cm tall',
    weight: 'a few g',
    lifespan: 'up to ~10 years',
    speed: 'glides on one muscular foot, very slowly',
    depth: '0-60 m, mostly between the tides',
    range: 'NE Atlantic; brought to NW Atlantic coasts',
    eats: 'algae, diatoms scraped off rocks',
    fact: 'At low tide it shuts its shell with a trapdoor and waits for the sea.',
  },
  // Representative: the common prawn (serrated rostrum, glassy body).
  shrimp: {
    latin: 'Palaemon serratus',
    length: 'up to 11 cm',
    weight: 'a few g',
    lifespan: 'up to ~5 years',
    speed: 'walks and swims; tail-flicks backwards to escape',
    depth: '0-50 m',
    range: 'NE Atlantic and Mediterranean',
    eats: 'tiny crustaceans, worms, algae, scraps',
    fact: 'Its body is almost see-through, so only its speckles and gut show.',
  },
  // Representative: the common hermit crab, which favours whelk shells.
  hermitcrab: {
    latin: 'Pagurus bernhardus',
    length: 'up to ~8 cm body',
    weight: 'not well recorded',
    lifespan: 'up to ~5 years',
    speed: 'walks, dragging its shell along',
    depth: '0-200 m, mostly above 80 m',
    range: 'NE Atlantic, Iceland to Portugal',
    eats: 'scraps, worms, small shellfish, detritus',
    fact: 'As it grows it moves into bigger shells, sometimes fighting for them.',
  },
  // Representative: the purple sea urchin of Pacific kelp forests.
  urchin: {
    latin: 'Strongylocentrotus purpuratus',
    length: 'shell up to ~10 cm across',
    weight: 'not well recorded',
    lifespan: 'often 20 years; maybe up to 70',
    speed: 'creeps on hundreds of tiny tube feet',
    depth: '0-160 m',
    range: 'Pacific coast of North America',
    eats: 'kelp, other seaweed',
    fact: 'Without sea otters to eat them, they can mow down whole kelp forests.',
  },
  // Representative: the dark blue European lobster.
  lobster: {
    latin: 'Homarus gammarus',
    length: 'up to ~60 cm',
    weight: 'up to ~6 kg',
    lifespan: 'up to ~70 years',
    speed: 'walks; flips its tail to shoot backwards',
    depth: '0-150 m, mostly above 50 m',
    range: 'NE Atlantic, Norway to Morocco; Mediterranean',
    eats: 'crabs, shellfish, worms, urchins, fish',
    fact: 'It is blue-black when alive and only turns red when cooked.',
  },
  // The Japanese spider crab: huge legs, deep slopes, orange shell.
  spidercrab: {
    latin: 'Macrocheira kaempferi',
    length: 'leg span up to ~3.7 m',
    weight: 'up to ~19 kg',
    lifespan: 'possibly up to 100 years',
    speed: 'slow, stilt-legged walker',
    depth: '50-600 m',
    range: 'Pacific waters around Japan',
    eats: 'dead animals, shellfish, algae',
    fact: 'It has the widest leg span of any arthropod alive.',
  },
  isopod: {
    latin: 'Bathynomus giganteus',
    length: 'up to ~50 cm',
    weight: 'up to ~2 kg',
    lifespan: 'unknown',
    speed: 'slow crawler; can swim upside down',
    depth: '310-2,300 m, mostly 365-730 m',
    range: 'Gulf of Mexico, Caribbean, W Atlantic',
    eats: 'dead whales and fish, slow animals',
    fact: 'One kept in a Japanese aquarium went over five years without eating.',
  },
  seapig: {
    latin: 'Scotoplanes globosa',
    length: 'up to ~15 cm',
    weight: 'unknown',
    lifespan: 'unknown',
    speed: 'plods over mud on water-filled tube feet',
    depth: '545-6,700 m, mostly above 2,000 m',
    range: 'deep ocean floors, e.g. off California',
    eats: 'fresh organic bits in the mud',
    fact: 'It walks on legs it inflates by pumping water into them.',
  },
  // Representative: the globe skimmer, the dragonfly that crosses oceans.
  dragonfly: {
    latin: 'Pantala flavescens',
    length: 'up to ~5 cm; wings ~8 cm across',
    weight: 'about 0.3 g',
    lifespan: 'unknown; larva grows up in ~6-9 weeks',
    speed: 'glides for hours on high winds',
    depth: 'never enters water; hunts above it',
    range: 'warm regions worldwide',
    eats: 'midges, mosquitoes, small flying insects',
    fact: 'Over generations it loops ~18,000 km, crossing the Indian Ocean.',
  },
  tern: {
    latin: 'Sterna hirundo',
    length: 'up to 35 cm; wingspan up to ~1 m',
    weight: 'up to ~150 g',
    lifespan: 'up to 33 years',
    speed: 'hovers, then plunges headfirst',
    depth: 'shallow plunge dives, under 1 m',
    range: 'breeds across the north; winters on southern coasts',
    eats: 'small fish, shrimp, insects',
    fact: 'Each autumn it flies from Europe to Africa or North to South America.',
  },
  gull: {
    latin: 'Larus argentatus',
    length: 'up to 67 cm; wingspan up to 1.55 m',
    weight: 'up to ~1.5 kg',
    lifespan: 'up to ~30 years',
    speed: 'flaps and soars; follows boats',
    depth: 'grabs from the surface; rarely goes under',
    range: 'coasts of NW Europe and the North Atlantic',
    eats: 'fish, crabs, shellfish, eggs, scraps',
    fact: 'Chicks peck the red spot on a parent\'s bill to make it cough up food.',
  },
  pelican: {
    latin: 'Pelecanus occidentalis',
    length: 'up to 1.5 m; wingspan up to ~2.3 m',
    weight: 'up to ~5.5 kg',
    lifespan: 'up to 43 years',
    speed: 'glides low over waves; plunges from up to 20 m',
    depth: 'stays near the surface after a plunge',
    range: 'coasts of the Americas',
    eats: 'small schooling fish',
    fact: 'Air sacs under its skin cushion the splash when it dives bill first.',
  },
  gannet: {
    latin: 'Morus bassanus',
    length: 'up to 1 m; wingspan up to 1.8 m',
    weight: 'up to ~3.6 kg',
    lifespan: 'up to 37 years',
    speed: 'hits the sea at up to ~100 km/h',
    depth: 'usually 3-5 m; can swim down past 20 m',
    range: 'North Atlantic',
    eats: 'mackerel, herring, sandeels',
    fact: 'It has no outer nostrils, so water cannot be forced up its beak in a dive.',
  },
  inkling: {
    latin: 'Atramentum minimus (made up)',
    length: 'up to one pen stroke',
    weight: 'about one drop of ink',
    lifespan: 'until the page is turned',
    speed: 'as fast as the pen that draws it',
    depth: '0-5 m, the first page of the sea',
    range: 'tide pools in the margins of sketchbooks',
    eats: 'stray dots, crumbs, smaller doodles',
    fact: 'It was drawn with a pen on the very first page, and swam off before the ink dried.',
  },
  // Representative: the black goby, a seagrass goby with a sucker disc.
  goby: {
    latin: 'Gobius niger',
    length: 'up to ~25 cm, usually under 15 cm',
    weight: 'not well recorded',
    lifespan: 'up to 5 years',
    speed: 'rests on the bottom, darts in short hops',
    depth: '1-96 m, mostly above 50 m',
    range: 'NE Atlantic, Mediterranean, Black Sea, Baltic',
    eats: 'small crustaceans, worms, snails, small fish',
    fact: 'Its pelvic fins are fused into a sucker disc, so it can cling on.',
  },
  perchfry: {
    latin: 'Perca fluviatilis',
    length: 'up to 60 cm',
    weight: 'up to ~4.8 kg',
    lifespan: 'up to 22 years',
    speed: 'steady swimmer; stalks, then darts',
    depth: 'mostly shallow, 0-30 m',
    range: 'Europe and N Asia: lakes, rivers, Baltic bays',
    eats: 'insect larvae, small crustaceans, fish',
    fact: 'Young perch shoal for safety; big perch happily eat small perch.',
  },
  // Representative: the threadfin butterflyfish (eye band, false eyespot, chevrons).
  butterfly: {
    latin: 'Chaetodon auriga',
    length: 'up to ~23 cm',
    weight: 'not well recorded',
    lifespan: 'not well known',
    speed: 'slow, but pivots in its own length',
    depth: '0-60 m',
    range: 'Indo-Pacific, Red Sea to Hawaii',
    eats: 'worms, coral polyps, anemones, algae',
    fact: 'A false eyespot near its tail fools predators about which way it will flee.',
  },
  barracuda: {
    latin: 'Sphyraena barracuda',
    length: 'up to 2 m',
    weight: 'up to ~50 kg',
    lifespan: 'up to ~18 years',
    speed: 'hangs still, then lunges at ~40 km/h',
    depth: '0-100 m, mostly 3-30 m',
    range: 'warm seas worldwide, except the E Pacific',
    eats: 'fish, squid',
    fact: 'It hunts by sight and may strike at anything shiny that flashes like a fish.',
  },
  // Atlantic bluefin: the classic big tuna of the Atlantic and Mediterranean.
  tuna: {
    latin: 'Thunnus thynnus',
    length: 'up to ~4.6 m',
    weight: 'up to ~680 kg',
    lifespan: 'up to 30+ years',
    speed: 'tireless cruiser; bursts often quoted ~70 km/h',
    depth: '0-1,000 m, mostly above 100 m',
    range: 'Atlantic Ocean and Mediterranean',
    eats: 'fish, squid, crustaceans',
    fact: 'It keeps its body far warmer than the sea, unlike most fish.',
  },
  // Family Myctophidae; representative: the spotted lanternfish.
  lanternfish: {
    latin: 'Myctophum punctatum (Myctophidae)',
    length: 'up to 11 cm',
    weight: 'a few g',
    lifespan: 'not well known',
    speed: 'climbs hundreds of metres every night',
    depth: '0-1,000 m; nearer the surface at night',
    range: 'North Atlantic and Mediterranean',
    eats: 'copepods, krill, other plankton',
    fact: 'Lanternfish rise each night in the largest daily migration on Earth.',
  },
  viperfish: {
    latin: 'Chauliodus sloani',
    length: 'up to 35 cm',
    weight: 'unknown',
    lifespan: 'poorly known; maybe 10+ years',
    speed: 'hangs still, then lunges',
    depth: '200-4,700 m, mostly 500-1,000 m',
    range: 'tropical and temperate oceans worldwide',
    eats: 'lanternfish and other fish, shrimp',
    fact: 'Its fangs are so long they do not fit inside its closed mouth.',
  },
  loosejaw: {
    latin: 'Malacosteus niger',
    length: 'up to ~25 cm',
    weight: 'unknown',
    lifespan: 'unknown',
    speed: 'drifts, then strikes with jaws flung open',
    depth: '500-3,900 m',
    range: 'tropical and temperate oceans worldwide',
    eats: 'mostly copepods; also shrimp, small fish',
    fact: 'It shines a red light that most deep-sea animals cannot see at all.',
  },
  snailfish: {
    latin: 'Pseudoliparis swirei',
    length: 'up to ~29 cm',
    weight: 'up to ~160 g',
    lifespan: 'unknown',
    speed: 'slow, sculling with long soft fins',
    depth: '6,200-8,100 m',
    range: 'Mariana Trench, W Pacific',
    eats: 'amphipods, small crustaceans',
    fact: 'Its skull never fully hardens, which helps it live under crushing pressure.',
  },
} as const satisfies Record<
  | 'shorecrab' | 'periwinkle' | 'shrimp' | 'hermitcrab' | 'urchin' | 'lobster' | 'spidercrab' | 'isopod' | 'seapig'
  | 'dragonfly' | 'tern' | 'gull' | 'pelican' | 'gannet'
  | 'inkling' | 'goby' | 'perchfry' | 'butterfly' | 'barracuda' | 'tuna'
  | 'lanternfish' | 'viperfish' | 'loosejaw' | 'snailfish',
  GuideEntry
>;
