import type { LevelDef } from './types';

/**
 * Beach 6, Fog & Kelp: a cold Pacific coast under a lighthouse (see
 * docs/inkcrab-levels.md). Its idea is not being seen: sea fog drifts
 * along the beach, hiding what's coming but hiding you too, and heaps of
 * washed-up kelp are cover nothing can see or smell through, with sand
 * hoppers to eat in them. Dungeness crabs hunt by sight, a raccoon by
 * smell (fog or no fog), a kingfisher from the sky. Small prey: kelp crabs.
 */
const KELP: Pick<LevelDef, 'fry' | 'ground'> = { fry: 'kelpcrab', ground: 'grey' };

export const BEACH_6: readonly LevelDef[] = [
  {
    ...KELP,
    id: 'kelp-wrack', name: 'Kelp Wrack', seed: 601, width: 64, height: 32, parTime: 150,
    hint: 'Heaps of kelp washed up on the sand. Down among the kelp nothing can see you, and sand hoppers live in it.',
    profile: [[0, 18], [63, 20]],
    kelp: [[20, 6], [42, 5]],
    startCol: 6,
    shells: [['blackturban', 14, 0], ['kelpsnail', 50, 0]],
    food: { surface: 12, buried: 8, shallow: 5 },
    critters: [{ count: 1, sizes: [3, 3], species: 'dungeness' }],
    teach: ['kelp'],
  },
  {
    ...KELP,
    id: 'sea-fog', name: 'Sea Fog', seed: 602, width: 72, height: 34, parTime: 200,
    hint: 'Fog rolls in off the sea. In it you see only what\'s close, but hunters can\'t see you far either.',
    profile: [[0, 19], [71, 21]],
    fog: { banks: [[36, 22]], drift: 0.4 },
    kelp: [[26, 5]],
    startCol: 6,
    shells: [['blackturban', 12, 0], ['kelpsnail', 30, 0], ['kellets', 58, 0]],
    food: { surface: 13, buried: 12, shallow: 6 },
    critters: [{ count: 2, sizes: [2, 3], species: 'dungeness' }],
    teach: ['fog'],
  },
  {
    ...KELP,
    id: 'dungeness', name: 'Dungeness', seed: 603, width: 76, height: 34, parTime: 250,
    hint: 'Dungeness crabs walk the sand after smaller crabs. Inked red, they can catch you: slip under the kelp out of their sight, or hide in your shell.',
    profile: [[0, 19], [75, 21]],
    fog: { banks: [[60, 18]], drift: -0.3 },
    kelp: [[18, 5], [38, 6], [62, 5]],
    startCol: 6,
    shells: [['blackturban', 13, 0], ['kelpsnail', 32, 0], ['kellets', 66, 0]],
    food: { surface: 13, buried: 13, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'dungeness' }, { count: 1, sizes: [5, 5], species: 'dungeness' }],
    teach: ['hide'],
  },
  {
    ...KELP,
    id: 'under-the-wrack', name: 'Under the Wrack', seed: 604, width: 76, height: 36, parTime: 300,
    hint: 'A Kellet\'s whelk lies buried under the big kelp heap. Dig down to it from among the kelp, where nothing can see you digging.',
    profile: [[0, 19], [75, 21]],
    fog: { banks: [[20, 16]], drift: 0.3 },
    kelp: [[24, 4], [46, 9]],
    startCol: 6,
    shells: [['blackturban', 12, 0], ['kelpsnail', 28, 0], ['kellets', 50, 4]],
    food: { surface: 13, buried: 15, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'dungeness' }, { count: 1, sizes: [5, 5], species: 'dungeness' }],
    teach: ['buried'],
  },
  {
    ...KELP,
    id: 'fog-bank', name: 'Fog Bank', seed: 605, width: 92, height: 36, parTime: 380,
    hint: 'Two banks of fog drift down the beach. The Oregon triton is out at the far end: watch for red ink coming out of the fog.',
    profile: [[0, 20], [91, 22]],
    fog: { banks: [[30, 20], [72, 18]], drift: 0.6 },
    kelp: [[22, 5], [50, 6], [76, 5]],
    startCol: 6,
    shells: [['blackturban', 12, 0], ['kelpsnail', 24, 0], ['kellets', 46, 0], ['oregontriton', 84, 0]],
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'dungeness' }, { count: 1, sizes: [6, 6], species: 'dungeness' }],
  },
  {
    ...KELP,
    id: 'kingfisher', name: 'Kingfisher', seed: 606, width: 88, height: 36, parTime: 420,
    hint: 'A kingfisher hovers over the beach. When its red shadow tightens on you, get under the kelp or into the fog, or hide in your shell.',
    profile: [[0, 20], [87, 22]],
    fog: { banks: [[56, 16]], drift: -0.4 },
    kelp: [[20, 5], [40, 5], [66, 6]],
    startCol: 6,
    shells: [['blackturban', 14, 0], ['kelpsnail', 30, 0], ['kellets', 48, 0], ['oregontriton', 72, 0]],
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'dungeness' }],
    birds: [{ count: 1, size: 6, species: 'kingfisher' }],
    teach: ['sky'],
  },
  {
    ...KELP,
    id: 'raccoon', name: 'Raccoon Tracks', seed: 607, width: 96, height: 38, parTime: 500,
    hint: 'A raccoon noses along the strandline. It hunts by smell: the fog won\'t hide you, but the kelp will.',
    profile: [[0, 21], [40, 22], [95, 23]],
    fog: { banks: [[40, 24]], drift: 0.3 },
    kelp: [[18, 5], [34, 6], [54, 5], [74, 6]],
    startCol: 6,
    shells: [['blackturban', 12, 0], ['kelpsnail', 26, 0], ['kellets', 46, 0], ['oregontriton', 80, 0]],
    food: { surface: 15, buried: 18, shallow: 8, start: 6 },
    critters: [{ count: 1, sizes: [6, 6], species: 'raccoon' }, { count: 2, sizes: [1, 4], species: 'dungeness' }],
    teach: ['raccoon'],
  },
  {
    ...KELP,
    id: 'lighthouse-point', name: 'Lighthouse Point', seed: 608, width: 96, height: 38, parTime: 560,
    hint: 'Rocks under the lighthouse, with the Oregon triton buried among them. Fog, kelp, Dungeness crabs and the kingfisher.',
    profile: [[0, 20], [95, 23]],
    rocks: [[44, 21, 2.2], [56, 22, 2.6]],
    fog: { banks: [[70, 22]], drift: -0.5 },
    kelp: [[20, 5], [36, 4], [64, 6], [82, 5]],
    startCol: 6,
    shells: [['blackturban', 12, 0], ['kelpsnail', 24, 0], ['kellets', 70, 0], ['oregontriton', 50, 4]],
    food: { surface: 15, buried: 20, shallow: 8, start: 6 },
    critters: [{ count: 2, sizes: [2, 5], species: 'dungeness' }, { count: 1, sizes: [5, 5], species: 'raccoon' }],
    birds: [{ count: 1, size: 6, species: 'kingfisher' }],
  },
  {
    ...KELP,
    id: 'pea-souper', name: 'Pea Souper', seed: 609, width: 104, height: 40, parTime: 680,
    hint: 'The thickest fog of the coast. The wavy turban is at the far end of the beach: feel your way, and keep the kelp close.',
    profile: [[0, 22], [103, 25]],
    fog: { banks: [[26, 30], [76, 34]], drift: 0.35 },
    kelp: [[16, 5], [34, 5], [52, 6], [70, 5], [88, 6]],
    startCol: 6,
    shells: [['blackturban', 12, 0], ['kelpsnail', 22, 0], ['kellets', 42, 0], ['oregontriton', 64, 0], ['wavyturban', 96, 0]],
    food: { surface: 16, buried: 22, shallow: 9, start: 8 },
    critters: [{ count: 2, sizes: [2, 5], species: 'dungeness' }, { count: 1, sizes: [6, 6], species: 'raccoon' }],
    birds: [{ count: 1, size: 6, species: 'kingfisher' }],
  },
  {
    ...KELP,
    id: 'the-lighthouse', name: 'The Lighthouse', seed: 610, width: 120, height: 42, parTime: 900,
    hint: 'Every shell of the kelp coast, from the black turban by the start to the wavy turban under the lighthouse.',
    profile: [[0, 22], [60, 24], [119, 26]],
    rocks: [[84, 25, 2.4]],
    fog: { banks: [[30, 26], [90, 28]], drift: 0.45 },
    kelp: [[18, 5], [36, 6], [56, 5], [74, 6], [96, 5], [108, 5]],
    startCol: 6,
    shells: [['blackturban', 12, 0], ['kelpsnail', 26, 0], ['kellets', 46, 0], ['oregontriton', 70, 0], ['wavyturban', 110, 0]],
    food: { surface: 18, buried: 28, shallow: 11, start: 10 },
    critters: [{ count: 2, sizes: [2, 5], species: 'dungeness' }, { count: 1, sizes: [6, 6], species: 'dungeness' }, { count: 1, sizes: [6, 6], species: 'raccoon' }],
    birds: [{ count: 1, size: 6, species: 'kingfisher' }],
  },
];
