import type { LevelDef } from './types';

/**
 * Beach 8, Monsoon Harbour: a fishing village on the Malabar coast in the
 * south-west monsoon (see docs/inkcrab-levels.md). Its idea is the monsoon:
 * squalls come and go on a steady rhythm. While it pours, mud crabs and
 * the Brahminy kite can't find you, the rain washes worms out and wet sand
 * digs fast; in the dry spells between, shelter under the boats drawn up
 * on the sand and the stilt houses, where no bird can stoop. Shells lie up
 * on top of them. A water monitor hunts by taste, rain or no rain. Small
 * prey: sand bubbler crabs.
 */
const HARBOUR: Pick<LevelDef, 'fry'> = { fry: 'bubbler' };

export const BEACH_8: readonly LevelDef[] = [
  {
    ...HARBOUR,
    id: 'monsoon-shore', name: 'Monsoon Shore', seed: 801, width: 64, height: 32, parTime: 150,
    hint: 'Fishing boats lie upturned on the sand. Under one no bird can reach you, and a babylon shell lies up on top: build a ramp of sand to climb on.',
    profile: [[0, 18], [63, 20]],
    startCol: 6,
    decks: [[26, 7, 2, 'boat']],
    shells: [['auger', 14, 0], ['babylon', 29, 0]],
    food: { surface: 13, buried: 8, shallow: 5 },
    teach: ['deck'],
  },
  {
    ...HARBOUR,
    id: 'first-rain', name: 'First Rain', seed: 802, width: 72, height: 34, parTime: 200,
    hint: 'Here comes the monsoon. While it pours, hunters can\'t see far, birds stay down and worms wash out. The rain clock shows when it\'s due.',
    profile: [[0, 19], [71, 21]],
    startCol: 6,
    decks: [[38, 6, 2, 'boat']],
    shells: [['auger', 14, 0], ['babylon', 30, 0], ['cone', 56, 0]],
    rain: { period: 40, pour: 15, offset: 14 },
    food: { surface: 13, buried: 12, shallow: 6 },
    critters: [{ count: 1, sizes: [3, 3], species: 'mudcrab' }],
    teach: ['rain'],
  },
  {
    ...HARBOUR,
    id: 'mud-crabs', name: 'Mud Crabs', seed: 803, width: 76, height: 34, parTime: 250,
    hint: 'Mud crabs hunt by sight. Inked red, they can catch you: hide in your shell, or wait for the rain to blind them.',
    profile: [[0, 19], [75, 21]],
    startCol: 6,
    decks: [[44, 6, 2, 'boat']],
    shells: [['auger', 12, 0], ['babylon', 30, 0], ['cone', 60, 0]],
    rain: { period: 42, pour: 15, offset: 10 },
    food: { surface: 13, buried: 13, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'mudcrab' }, { count: 1, sizes: [5, 5], species: 'mudcrab' }],
    teach: ['hide'],
  },
  {
    ...HARBOUR,
    id: 'under-the-boat', name: 'Under the Boat', seed: 804, width: 76, height: 36, parTime: 300,
    hint: 'A cone shell lies buried under the big boat. Dig down to it in the shade, where no bird can see you: the rain makes the digging quick.',
    profile: [[0, 19], [75, 21]],
    startCol: 6,
    decks: [[46, 9, 2, 'boat']],
    shells: [['auger', 12, 0], ['babylon', 28, 0], ['cone', 50, 4]],
    rain: { period: 42, pour: 15, offset: 8 },
    food: { surface: 13, buried: 15, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'mudcrab' }, { count: 1, sizes: [5, 5], species: 'mudcrab' }],
    teach: ['buried'],
  },
  {
    ...HARBOUR,
    id: 'stilt-village', name: 'Stilt Village', seed: 805, width: 92, height: 36, parTime: 380,
    hint: 'A row of stilt houses, a shell up on each. Build your way up to the spider conch on the far one, and shelter underneath when hunters come.',
    profile: [[0, 20], [91, 22]],
    startCol: 6,
    decks: [[24, 6, 2, 'house'], [44, 6, 3, 'house'], [70, 7, 3, 'house']],
    shells: [['auger', 12, 0], ['babylon', 26, 0], ['cone', 47, 0], ['spiderconch', 73, 0]],
    rain: { period: 44, pour: 15, offset: 6 },
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'mudcrab' }, { count: 1, sizes: [5, 5], species: 'mudcrab' }],
  },
  {
    ...HARBOUR,
    id: 'brahminy-kite', name: 'Brahminy Kite', seed: 806, width: 88, height: 36, parTime: 420,
    hint: 'A Brahminy kite hunts over the harbour. When its red shadow tightens on you, get under a boat or hide in your shell. It won\'t hunt in the rain.',
    profile: [[0, 20], [87, 22]],
    startCol: 6,
    decks: [[20, 6, 2, 'boat'], [44, 5, 1, 'rack'], [66, 7, 2, 'boat']],
    shells: [['auger', 14, 0], ['babylon', 30, 0], ['cone', 54, 0], ['spiderconch', 69, 0]],
    rain: { period: 45, pour: 14, offset: 4 },
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'mudcrab' }],
    birds: [{ count: 1, size: 6, species: 'brahminy' }],
    teach: ['sky'],
  },
  {
    ...HARBOUR,
    id: 'water-monitor', name: 'Water Monitor', seed: 807, width: 96, height: 38, parTime: 500,
    hint: 'A water monitor prowls the boats. It hunts by taste, so the rain won\'t hide you from it. It\'s slow: outrun it, or climb up where it can\'t follow.',
    profile: [[0, 21], [40, 22], [95, 23]],
    startCol: 6,
    decks: [[30, 6, 2, 'boat'], [58, 6, 3, 'house'], [80, 6, 1, 'rack']],
    shells: [['auger', 12, 0], ['babylon', 26, 0], ['cone', 44, 0], ['spiderconch', 61, 0]],
    rain: { period: 45, pour: 15, offset: 2 },
    food: { surface: 15, buried: 18, shallow: 8, start: 6 },
    critters: [{ count: 1, sizes: [5, 5], species: 'monitor' }, { count: 2, sizes: [1, 3], species: 'mudcrab' }],
    teach: ['monitor'],
  },
  {
    ...HARBOUR,
    id: 'drying-racks', name: 'Drying Racks', seed: 808, width: 96, height: 38, parTime: 560,
    hint: 'Fish drying on the racks, rocks below the sea wall, and everyone out hunting. The spider conch is buried among the rocks.',
    profile: [[0, 20], [95, 23]],
    rocks: [[44, 21, 2.2], [56, 22, 2.6]],
    startCol: 6,
    decks: [[20, 5, 1, 'rack'], [30, 5, 1, 'rack'], [68, 8, 2, 'boat']],
    shells: [['auger', 12, 0], ['babylon', 22, 0], ['cone', 38, 0], ['spiderconch', 50, 4]],
    rain: { period: 45, pour: 14, offset: 4 },
    food: { surface: 15, buried: 20, shallow: 8, start: 6 },
    critters: [{ count: 2, sizes: [2, 5], species: 'mudcrab' }, { count: 1, sizes: [4, 4], species: 'monitor' }],
    birds: [{ count: 1, size: 6, species: 'brahminy' }],
  },
  {
    ...HARBOUR,
    id: 'monsoon-break', name: 'Monsoon Break', seed: 809, width: 104, height: 40, parTime: 680,
    hint: 'The rains hold off: short squalls, long dry spells, and every hunter out. Shelter under the boats and make the most of each downpour.',
    profile: [[0, 22], [103, 25]],
    startCol: 6,
    decks: [[22, 6, 2, 'boat'], [44, 7, 3, 'house'], [64, 5, 1, 'rack'], [86, 8, 3, 'house']],
    shells: [['auger', 12, 0], ['babylon', 26, 0], ['cone', 47, 0], ['spiderconch', 66, 0], ['volute', 90, 0]],
    rain: { period: 60, pour: 12, offset: 20 },
    food: { surface: 16, buried: 22, shallow: 9, start: 8 },
    critters: [{ count: 2, sizes: [2, 5], species: 'mudcrab' }, { count: 1, sizes: [6, 6], species: 'monitor' }],
    birds: [{ count: 1, size: 6, species: 'brahminy' }],
  },
  {
    ...HARBOUR,
    id: 'monsoon-harbour', name: 'Monsoon Harbour', seed: 810, width: 120, height: 42, parTime: 900,
    hint: 'Every shell of the harbour, from the auger by the start to the Indian volute up on the biggest stilt house.',
    profile: [[0, 22], [60, 24], [119, 26]],
    rocks: [[84, 25, 2.4]],
    startCol: 6,
    decks: [[20, 6, 2, 'boat'], [36, 5, 1, 'rack'], [52, 7, 3, 'house'], [70, 7, 2, 'boat'], [100, 9, 3, 'house']],
    shells: [['auger', 12, 0], ['babylon', 28, 0], ['cone', 55, 0], ['spiderconch', 73, 3], ['volute', 104, 0]],
    rain: { period: 48, pour: 15, offset: 10 },
    food: { surface: 18, buried: 28, shallow: 11, start: 10 },
    critters: [{ count: 2, sizes: [2, 5], species: 'mudcrab' }, { count: 1, sizes: [6, 6], species: 'monitor' }],
    birds: [{ count: 1, size: 6, species: 'brahminy' }],
  },
];
