import type { LevelDef } from './types';

/**
 * Beach 3, Tide Pool Notes: a cold granite coast with rock pools (see
 * docs/inkcrab-levels.md). Its idea is the tide: the sea rises from the
 * right-hand edge and goes out again on a steady rhythm, flooding all it
 * can reach and leaving the pools full. Water is safe but slow. Fish swim
 * in it (blennies, then sculpins); an octopus reaches out of its crevice
 * in the rock; gulls walk the shore at low water. A few rows of sand lie
 * over granite, so there's only so far to dig. Small prey: young shore crabs.
 */
const POOLS: Pick<LevelDef, 'fry' | 'granite'> = { fry: 'shorecrab', granite: 5 };

export const BEACH_3: readonly LevelDef[] = [
  {
    ...POOLS,
    id: 'first-tide', name: 'First Tide', seed: 301, width: 64, height: 30, parTime: 150,
    hint: 'The tide comes in from the sea and goes out again. Water is safe, just slow. Watch the tide clock.',
    profile: [[0, 10], [24, 12], [44, 17], [63, 20]],
    tide: { low: 22, high: 14, period: 60 },
    tideBrings: { food: 4 },
    startCol: 6,
    shells: [['flatwinkle', 3, 18, 0], ['dogwhelk', 4, 50, 0]],
    food: { surface: 12, buried: 8, shallow: 5 },
    critters: [{ count: 2, sizes: [1, 2], species: 'shorecrab' }],
    teach: ['tide'],
  },
  {
    ...POOLS,
    id: 'rock-shelf', name: 'Rock Shelf', seed: 302, width: 68, height: 32, parTime: 190,
    hint: 'The painted top shell sits on a granite shelf. Rock won\'t dig: build steps with the sand you carry.',
    profile: [[0, 11], [28, 13], [29, 8], [38, 8], [39, 15], [67, 21]],
    rocks: [[33, 10, 4.2]],
    tide: { low: 23, high: 15, period: 64 },
    tideBrings: { food: 4 },
    startCol: 6,
    shells: [['flatwinkle', 3, 16, 0], ['dogwhelk', 4, 24, 0], ['paintedtop', 5, 33, 0]],
    food: { surface: 12, buried: 10, shallow: 5 },
    critters: [{ count: 2, sizes: [1, 3], species: 'shorecrab' }],
  },
  {
    ...POOLS,
    id: 'blenny-pool', name: 'Blenny Pool', seed: 303, width: 72, height: 32, parTime: 230,
    hint: 'Red fish swim in the pools and the incoming tide. Small ones are food; big ones hunt you in the water.',
    profile: [[0, 11], [30, 13], [52, 17], [71, 21]],
    pools: [[20, 6, 3], [40, 7, 3]],
    tide: { low: 23, high: 15, period: 66 },
    tideBrings: { food: 4 },
    startCol: 6,
    shells: [['flatwinkle', 3, 12, 0], ['dogwhelk', 4, 36, 0], ['paintedtop', 5, 60, 0]],
    food: { surface: 12, buried: 10, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 2], species: 'blenny' }, { count: 2, sizes: [4, 5], species: 'blenny' }, { count: 2, sizes: [1, 3], species: 'shorecrab' }],
    teach: ['hide'],
  },
  {
    ...POOLS,
    id: 'strandline', name: 'Strandline', seed: 304, width: 76, height: 34, parTime: 300,
    hint: 'A necklace shell lies buried below the tide line. Dig for it at low water, before the sea floods your hole.',
    profile: [[0, 11], [30, 13], [50, 17], [75, 20]],
    pools: [[24, 6, 3]],
    tide: { low: 24, high: 15, period: 70 },
    tideBrings: { food: 5 },
    startCol: 6,
    shells: [['flatwinkle', 3, 12, 0], ['dogwhelk', 4, 22, 0], ['paintedtop', 5, 34, 0], ['necklace', 6, 58, 3]],
    food: { surface: 12, buried: 14, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'blenny' }, { count: 1, sizes: [5, 5], species: 'blenny' }, { count: 2, sizes: [1, 4], species: 'shorecrab' }],
    teach: ['buried'],
  },
  {
    ...POOLS,
    id: 'pool-chain', name: 'Pool Chain', seed: 305, width: 88, height: 34, parTime: 360,
    hint: 'A chain of pools down the shore. Gulls walk it at low water; the sea and its fish fill it at high.',
    profile: [[0, 10], [30, 12], [60, 16], [87, 20]],
    pools: [[16, 5, 3], [36, 6, 3], [56, 6, 3]],
    tide: { low: 24, high: 14, period: 72 },
    tideBrings: { food: 5 },
    startCol: 6,
    shells: [['flatwinkle', 3, 10, 0], ['dogwhelk', 4, 28, 0], ['paintedtop', 5, 48, 0], ['necklace', 6, 74, 0]],
    food: { surface: 12, buried: 14, shallow: 6 },
    critters: [{ count: 3, sizes: [1, 5], species: 'blenny' }, { count: 1, sizes: [5, 6], species: 'gull' }, { count: 2, sizes: [1, 4], species: 'shorecrab' }],
  },
  {
    ...POOLS,
    id: 'octopus-garden', name: 'Octopus Garden', seed: 306, width: 84, height: 36, parTime: 420,
    hint: 'Octopuses live in crevices in the rock and reach out for passing crabs. Keep out of reach, or hide.',
    profile: [[0, 11], [32, 13], [58, 17], [83, 21]],
    pools: [[22, 6, 4], [46, 7, 4]],
    dens: [[21, 15], [53, 19]],
    tide: { low: 25, high: 15, period: 72 },
    tideBrings: { food: 5 },
    startCol: 6,
    shells: [['flatwinkle', 3, 12, 0], ['dogwhelk', 4, 20, 0], ['paintedtop', 5, 36, 0], ['necklace', 6, 70, 0]],
    food: { surface: 12, buried: 14, shallow: 6 },
    critters: [{ count: 2, sizes: [5, 7], species: 'octopus' }, { count: 2, sizes: [1, 4], species: 'blenny' }, { count: 2, sizes: [1, 4], species: 'shorecrab' }],
    teach: ['octopus'],
  },
  {
    ...POOLS,
    id: 'the-tide-brings', name: 'The Tide Brings', seed: 307, width: 92, height: 36, parTime: 520,
    hint: 'Each high tide washes something in. Wait for the frog shell to come in on the strandline.',
    profile: [[0, 10], [30, 12], [60, 16], [91, 21]],
    pools: [[40, 6, 3]],
    dens: [[46, 15]],
    tide: { low: 25, high: 14, period: 70 },
    tideBrings: { food: 5, shells: [['necklace', 6, 66], ['frogshell', 7, 62]] },
    startCol: 6,
    shells: [['flatwinkle', 3, 12, 0], ['dogwhelk', 4, 26, 0], ['paintedtop', 5, 50, 0]],
    food: { surface: 12, buried: 16, shallow: 7 },
    critters: [{ count: 1, sizes: [6, 7], species: 'octopus' }, { count: 2, sizes: [1, 6], species: 'sculpin' }, { count: 1, sizes: [6, 6], species: 'gull' }, { count: 2, sizes: [1, 5], species: 'shorecrab' }],
  },
  {
    ...POOLS,
    id: 'low-water', name: 'Low Water', seed: 308, width: 96, height: 38, parTime: 600,
    hint: 'Gulls on the rocks at low water, fish and octopuses in the pools. The frog shell is buried by the big pool.',
    profile: [[0, 11], [32, 13], [62, 17], [95, 22]],
    pools: [[20, 6, 3], [46, 8, 4], [72, 6, 3]],
    dens: [[45, 18], [78, 20]],
    tide: { low: 26, high: 15, period: 74 },
    tideBrings: { food: 5 },
    startCol: 6,
    shells: [['flatwinkle', 3, 12, 0], ['dogwhelk', 4, 18, 0], ['paintedtop', 5, 32, 0], ['necklace', 6, 60, 0], ['frogshell', 7, 40, 3]],
    food: { surface: 12, buried: 18, shallow: 7 },
    critters: [{ count: 2, sizes: [5, 7], species: 'octopus' }, { count: 3, sizes: [2, 7], species: 'sculpin' }, { count: 1, sizes: [6, 7], species: 'gull' }, { count: 2, sizes: [1, 5], species: 'shorecrab' }],
  },
  {
    ...POOLS,
    id: 'spring-tide', name: 'Spring Tide', seed: 309, width: 104, height: 40, parTime: 700,
    hint: 'A spring tide: it comes in higher and faster. The knobbed whelk waits on top of the rocks.',
    profile: [[0, 9], [10, 9], [26, 15], [64, 18], [103, 23]],
    rocks: [[6, 10, 3.5]],
    pools: [[40, 7, 3], [70, 7, 4]],
    dens: [[77, 21]],
    tide: { low: 27, high: 12, period: 56 },
    tideBrings: { food: 6 },
    startCol: 96,
    shells: [['flatwinkle', 3, 88, 0], ['dogwhelk', 4, 80, 0], ['paintedtop', 5, 68, 0], ['necklace', 6, 56, 0], ['frogshell', 7, 32, 0], ['knobbedwhelk', 8, 5, 0]],
    food: { surface: 12, buried: 18, shallow: 8 },
    critters: [{ count: 1, sizes: [7, 8], species: 'octopus' }, { count: 3, sizes: [2, 8], species: 'sculpin' }, { count: 2, sizes: [6, 8], species: 'gull' }, { count: 2, sizes: [1, 6], species: 'shorecrab' }],
  },
  {
    ...POOLS,
    id: 'the-last-pool', name: 'The Last Pool', seed: 310, width: 120, height: 42, parTime: 820,
    hint: 'Every shell of the rock pools, from the flat periwinkle to the knobbed whelk on the far headland.',
    profile: [[0, 10], [12, 10], [30, 16], [70, 19], [119, 24]],
    pools: [[44, 7, 3], [66, 8, 4], [92, 7, 3]],
    dens: [[65, 21], [99, 23]],
    tide: { low: 28, high: 15, period: 70 },
    tideBrings: { food: 6, shells: [['necklace', 6, 84]] },
    startCol: 112,
    shells: [['flatwinkle', 3, 104, 0], ['dogwhelk', 4, 96, 0], ['paintedtop', 5, 80, 0], ['frogshell', 7, 40, 3], ['knobbedwhelk', 8, 5, 0]],
    food: { surface: 14, buried: 22, shallow: 8 },
    critters: [{ count: 2, sizes: [6, 8], species: 'octopus' }, { count: 3, sizes: [2, 8], species: 'sculpin' }, { count: 2, sizes: [1, 4], species: 'blenny' }, { count: 2, sizes: [6, 8], species: 'gull' }, { count: 3, sizes: [1, 6], species: 'shorecrab' }],
  },
];
