import type { LevelDef } from './types';

/**
 * Beach 10, Moonlit Bay: a tropical reef bay on the Queensland coast on a
 * summer night, the last beach (see docs/inkcrab-levels.md). Its idea is
 * the night: clouds pass over the full moon on a steady rhythm, and while
 * it's dark what hunts by sight sees only close, and so do you. Glowing
 * plankton in the strand lights up wherever anything walks: you see the
 * hunters coming by their tracks, and in the dark they see you on it.
 * Horn-eyed ghost crabs hunt by sight; a coconut crab hunts by smell, dark
 * or not. Small prey: brittle stars. The grandest shells of the game, the
 * baler last.
 */
const BAY: Pick<LevelDef, 'fry' | 'ground'> = { fry: 'brittlestar', ground: 'moonlit' };

export const BEACH_10: readonly LevelDef[] = [
  {
    ...BAY,
    id: 'moonrise', name: 'Moonrise', seed: 1001, width: 64, height: 32, parTime: 150,
    hint: 'A full moon over the bay. The wet sand of the strand glows wherever anything walks on it: you\'ll see who\'s about by their tracks.',
    profile: [[0, 18], [63, 20]],
    startCol: 6,
    glow: [[20, 44]],
    shells: [['tigermoon', 3, 14, 0], ['gianttun', 4, 38, 0]],
    food: { surface: 13, buried: 9, shallow: 5 },
    teach: ['glow'],
  },
  {
    ...BAY,
    id: 'cloud-cover', name: 'Cloud Cover', seed: 1002, width: 72, height: 34, parTime: 200,
    hint: 'Clouds pass over the moon. In the dark you see only what\'s close, and so do the hunters. A horned helmet lies up on the coral rock.',
    profile: [[0, 19], [43, 20], [45, 15], [52, 15], [54, 20], [71, 21]],
    startCol: 6,
    glow: [[56, 68]],
    shells: [['tigermoon', 3, 14, 0], ['gianttun', 4, 32, 0], ['hornedhelmet', 5, 48, 0], ['hornedhelmet', 6, 62, 0]],
    moon: { period: 40, dark: 14, offset: 10 },
    food: { surface: 13, buried: 12, shallow: 6 },
    teach: ['moon'],
  },
  {
    ...BAY,
    id: 'horn-eyes', name: 'Horn Eyes', seed: 1003, width: 76, height: 34, parTime: 250,
    hint: 'Horn-eyed ghost crabs sprint the sand by night. Inked red, they can catch you: hide in your shell, or slip past them in the dark, off the glowing sand.',
    profile: [[0, 19], [75, 21]],
    rocks: [[34, 20, 1.8]],
    startCol: 6,
    glow: [[22, 30], [46, 62]],
    shells: [['tigermoon', 3, 12, 0], ['gianttun', 4, 28, 0], ['hornedhelmet', 5, 42, 0], ['hornedhelmet', 6, 64, 0]],
    moon: { period: 42, dark: 14, offset: 8 },
    food: { surface: 13, buried: 13, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'horneyed' }, { count: 1, sizes: [5, 5], species: 'horneyed' }],
    teach: ['hide'],
  },
  {
    ...BAY,
    id: 'turtle-nest', name: 'Turtle Nest', seed: 1004, width: 76, height: 36, parTime: 300,
    hint: 'A turtle dug her nest high on the beach, and a horned helmet lies buried beside it. Dig down to it: the dark hides your digging.',
    profile: [[0, 19], [40, 19], [46, 17], [56, 17], [62, 20], [75, 21]],
    startCol: 6,
    glow: [[62, 72]],
    shells: [['tigermoon', 3, 12, 0], ['gianttun', 4, 26, 0], ['hornedhelmet', 5, 37, 0], ['hornedhelmet', 6, 51, 4]],
    moon: { period: 42, dark: 15, offset: 6 },
    food: { surface: 13, buried: 15, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'horneyed' }, { count: 1, sizes: [5, 5], species: 'horneyed' }],
    teach: ['buried'],
  },
  {
    ...BAY,
    id: 'reef-flat', name: 'Reef Flat', seed: 1005, width: 92, height: 36, parTime: 380,
    hint: 'Shells lie strewn along the reef flat, a triton\'s trumpet at the far end. Pick your moments: the glowing sand gives you away in the dark.',
    profile: [[0, 20], [91, 22]],
    rocks: [[30, 21, 1.8], [62, 22, 2]],
    startCol: 6,
    glow: [[36, 54], [70, 84]],
    shells: [['tigermoon', 3, 12, 0], ['gianttun', 4, 26, 0], ['hornedhelmet', 5, 40, 0], ['hornedhelmet', 6, 56, 0], ['tritonstrumpet', 7, 80, 0]],
    moon: { period: 44, dark: 15, offset: 6 },
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'horneyed' }, { count: 1, sizes: [5, 5], species: 'horneyed' }],
  },
  {
    ...BAY,
    id: 'coconut-crab', name: 'Coconut Crab', seed: 1006, width: 88, height: 36, parTime: 420,
    hint: 'A coconut crab comes down from the palms. It hunts by smell, so the dark won\'t hide you from it. It\'s slow: outrun it, or hide in your shell.',
    profile: [[0, 20], [87, 22]],
    rocks: [[52, 21, 2]],
    startCol: 6,
    glow: [[24, 40], [60, 76]],
    shells: [['tigermoon', 3, 14, 0], ['gianttun', 4, 30, 0], ['hornedhelmet', 5, 42, 0], ['hornedhelmet', 6, 56, 0], ['tritonstrumpet', 7, 78, 0]],
    moon: { period: 44, dark: 14, offset: 4 },
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 1, sizes: [5, 5], species: 'coconutcrab' }, { count: 2, sizes: [1, 4], species: 'horneyed' }],
  },
  {
    ...BAY,
    id: 'glowing-tide', name: 'Glowing Tide', seed: 1007, width: 92, height: 36, parTime: 520,
    hint: 'A clear night and a glowing tide. Each high water washes something in along the shining strand: a triton\'s trumpet will come.',
    profile: [[0, 10], [30, 12], [60, 16], [91, 21]],
    tide: { low: 25, high: 14, period: 70 },
    tideBrings: { food: 5, shells: [['tritonstrumpet', 7, 62]] },
    startCol: 6,
    glow: [[40, 80]],
    shells: [['tigermoon', 3, 12, 0], ['gianttun', 4, 22, 0], ['hornedhelmet', 5, 32, 0], ['hornedhelmet', 6, 44, 0]],
    food: { surface: 15, buried: 18, shallow: 8, start: 6 },
    critters: [{ count: 2, sizes: [1, 4], species: 'horneyed' }],
  },
  {
    ...BAY,
    id: 'coral-rubble', name: 'Coral Rubble', seed: 1008, width: 96, height: 38, parTime: 560,
    hint: 'Coral rubble, the glowing strand, clouds coming and going and everyone out hunting. The triton\'s trumpet is buried among the coral.',
    profile: [[0, 20], [95, 23]],
    rocks: [[46, 21, 2.2], [58, 22, 2.6]],
    startCol: 6,
    glow: [[18, 34], [66, 86]],
    shells: [['tigermoon', 3, 12, 0], ['gianttun', 4, 24, 0], ['hornedhelmet', 5, 32, 0], ['hornedhelmet', 6, 40, 0], ['tritonstrumpet', 7, 52, 4]],
    moon: { period: 44, dark: 15, offset: 4 },
    food: { surface: 15, buried: 20, shallow: 8, start: 6 },
    critters: [{ count: 2, sizes: [2, 5], species: 'horneyed' }, { count: 1, sizes: [4, 4], species: 'coconutcrab' }],
  },
  {
    ...BAY,
    id: 'new-moon', name: 'New Moon', seed: 1009, width: 104, height: 40, parTime: 680,
    hint: 'Clouds bank up over the moon: long dark spells, short moonlight, and every hunter out. The baler waits up on the high dune.',
    profile: [[0, 22], [78, 24], [84, 19], [94, 19], [98, 25], [103, 25]],
    rocks: [[30, 23, 2], [60, 24, 2.2]],
    startCol: 6,
    glow: [[16, 26], [40, 56], [66, 78]],
    shells: [['tigermoon', 3, 12, 0], ['gianttun', 4, 26, 0], ['hornedhelmet', 5, 36, 0], ['hornedhelmet', 6, 54, 0], ['tritonstrumpet', 7, 68, 0], ['baler', 8, 89, 0]],
    moon: { period: 40, dark: 20, offset: 12 },
    food: { surface: 16, buried: 22, shallow: 9, start: 8 },
    critters: [{ count: 2, sizes: [2, 5], species: 'horneyed' }, { count: 1, sizes: [6, 6], species: 'coconutcrab' }],
  },
  {
    ...BAY,
    id: 'moonlit-bay', name: 'Moonlit Bay', seed: 1010, width: 120, height: 42, parTime: 900,
    hint: 'The last beach of all: every shell of the bay, from the tiger moon snail by the start to the great baler up on the highest dune.',
    profile: [[0, 22], [46, 24], [50, 21], [54, 24], [96, 26], [100, 20], [110, 20], [114, 26], [119, 26]],
    rocks: [[34, 23, 2], [78, 25, 2.4]],
    startCol: 6,
    glow: [[20, 30], [56, 76], [84, 94]],
    shells: [['tigermoon', 3, 12, 0], ['gianttun', 4, 28, 0], ['hornedhelmet', 5, 42, 0], ['hornedhelmet', 6, 60, 0], ['tritonstrumpet', 7, 70, 4], ['baler', 8, 105, 0]],
    moon: { period: 44, dark: 16, offset: 10 },
    food: { surface: 18, buried: 28, shallow: 11, start: 10 },
    critters: [{ count: 2, sizes: [2, 5], species: 'horneyed' }, { count: 1, sizes: [6, 6], species: 'coconutcrab' }],
  },
];
