import type { LevelDef } from './types';

/**
 * Beach 2, the Dune Sea: a desert running down into the ocean (see
 * docs/inkcrab-levels.md). Danger comes from above and below. Kestrels
 * hover over crabs out in the open and stoop; antlions wait at the bottom
 * of their pits; sandfish swim through the sand after crabs in their
 * tunnels; ravens walk the dunes and hop up walls. The top rows are loose
 * dune sand that pours into any hole; the packed sand under it holds. The
 * small prey is darkling beetles. Its own shells: a bleached desert snail,
 * the turban, the olive, the murex and the helmet at the top.
 */
const DUNE: Pick<LevelDef, 'fry' | 'loose'> = { fry: 'darkling', loose: 3 };

export const BEACH_2: readonly LevelDef[] = [
  {
    ...DUNE,
    id: 'shifting-sands', name: 'Shifting Sands', seed: 201, width: 60, height: 30, parTime: 140,
    hint: 'Dune sand is loose: dig into it and it pours back. Further down, the sand is packed and tunnels hold.',
    profile: [[0, 12], [14, 10], [28, 13], [42, 11], [59, 13]],
    startCol: 6,
    shells: [['desertsnail', 22, 0], ['nerite', 48, 5]],
    food: { surface: 12, buried: 10, shallow: 5 },
    critters: [{ count: 2, sizes: [1, 2], species: 'darkling' }],
  },
  {
    ...DUNE,
    id: 'dune-crest', name: 'Dune Crest', seed: 202, width: 64, height: 32, parTime: 180,
    hint: 'The turban shell sits up on the mesa. Build steps with the sand you carry: dropped sand stays put.',
    profile: [[0, 15], [30, 15], [31, 9], [42, 9], [43, 15], [63, 15]],
    startCol: 6,
    shells: [['desertsnail', 16, 0], ['turban', 36, 0]],
    food: { surface: 12, buried: 12, shallow: 5 },
    critters: [{ count: 2, sizes: [1, 3], species: 'darkling' }, { count: 2, sizes: [1, 3] }],
  },
  {
    ...DUNE,
    id: 'kestrel-shadow', name: 'Kestrel Shadow', seed: 203, width: 76, height: 32, parTime: 220,
    hint: 'A red shadow on the sand is a kestrel overhead. Get under the sand, or hide in your shell and let it strike.',
    profile: [[0, 13], [20, 14], [40, 13], [58, 15], [75, 14]],
    startCol: 8,
    shells: [['desertsnail', 26, 0], ['turban', 60, 0]],
    food: { surface: 12, buried: 14, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'darkling' }],
    birds: [{ count: 1, size: 5 }],
    teach: ['sky'],
  },
  {
    ...DUNE,
    id: 'under-the-dune', name: 'Under the Dune', seed: 204, width: 70, height: 36, parTime: 300,
    hint: 'An olive shell lies under the big dune. Dig through the loose sand to the packed sand below.',
    profile: [[0, 14], [18, 13], [34, 9], [44, 9], [58, 13], [69, 14]],
    startCol: 6,
    shells: [['desertsnail', 14, 0], ['turban', 60, 0], ['olive', 39, 7]],
    food: { surface: 12, buried: 16, shallow: 6, clams: [[30, 6], [48, 7]] },
    critters: [{ count: 2, sizes: [1, 4], species: 'darkling' }, { count: 2, sizes: [1, 4] }],
    birds: [{ count: 1, size: 4 }],
    teach: ['buried'],
  },
  {
    ...DUNE,
    id: 'antlion-alley', name: 'Antlion Alley', seed: 205, width: 84, height: 32, parTime: 360,
    hint: 'Pits slide you down to the antlion at the bottom. Small ones are food; fill a big one\'s pit with sand.',
    profile: [[0, 12], [30, 13], [60, 12], [83, 13]],
    pits: [[18, 3], [34, 4], [52, 3], [68, 4]],
    startCol: 6,
    shells: [['desertsnail', 10, 0], ['turban', 44, 0], ['olive', 76, 0]],
    food: { surface: 12, buried: 16, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 2], species: 'antlion' }, { count: 2, sizes: [5, 7], species: 'antlion' }, { count: 2, sizes: [1, 4], species: 'darkling' }],
    teach: ['pit'],
  },
  {
    ...DUNE,
    id: 'sandfish-shallows', name: 'Sandfish Shallows', seed: 206, width: 88, height: 36, parTime: 420,
    hint: 'Sandfish swim through the sand after crabs in tunnels. Kestrels hunt the open. Pick your moment.',
    profile: [[0, 11], [26, 12], [52, 14], [87, 13]],
    rocks: [[30, 24, 3], [64, 28, 3]],
    startCol: 8,
    shells: [['desertsnail', 18, 0], ['turban', 40, 3], ['olive', 72, 0]],
    food: { surface: 10, buried: 18, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 2], species: 'skink' }, { count: 2, sizes: [4, 6], species: 'skink' }, { count: 2, sizes: [1, 4], species: 'darkling' }],
    birds: [{ count: 1, size: 4 }],
    teach: ['sandfish'],
  },
  {
    ...DUNE,
    id: 'raven-ridge', name: 'Raven Ridge', seed: 207, width: 96, height: 36, parTime: 520,
    hint: 'Ravens walk the ridge and hop up walls, but they\'re too big for a tunnel. A murex lies down by the sea.',
    profile: [[0, 9], [20, 10], [40, 14], [70, 17], [95, 19]],
    pits: [[30, 3], [58, 3]],
    startCol: 6,
    shells: [['desertsnail', 14, 0], ['turban', 34, 0], ['olive', 52, 4], ['murex', 88, 0]],
    food: { surface: 12, buried: 18, shallow: 7 },
    critters: [{ count: 2, sizes: [5, 7], species: 'raven' }, { count: 2, sizes: [1, 6], species: 'antlion' }, { count: 2, sizes: [1, 5], species: 'darkling' }],
    birds: [{ count: 1, size: 5 }],
  },
  {
    ...DUNE,
    id: 'mirage', name: 'Mirage', seed: 208, width: 100, height: 38, parTime: 600,
    hint: 'The murex is buried between the pits. Sandfish below, kestrels above: dig fast and stay close to cover.',
    profile: [[0, 12], [30, 13], [50, 11], [70, 14], [99, 15]],
    pits: [[22, 3], [78, 4]],
    rocks: [[60, 30, 3.5]],
    startCol: 6,
    shells: [['desertsnail', 14, 0], ['turban', 34, 0], ['olive', 66, 0], ['murex', 50, 6]],
    food: { surface: 10, buried: 20, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 6], species: 'antlion' }, { count: 3, sizes: [2, 7], species: 'skink' }, { count: 2, sizes: [1, 5], species: 'darkling' }],
    birds: [{ count: 1, size: 6 }],
  },
  {
    ...DUNE, loose: 5,
    id: 'sandstorm', name: 'Sandstorm', seed: 209, width: 108, height: 40, parTime: 700,
    hint: 'Deep, loose sand and hunters everywhere. The helmet shell waits on top of the high dune.',
    profile: [[0, 10], [12, 10], [30, 17], [64, 18], [107, 20]],
    pits: [[44, 3], [80, 4]],
    startCol: 100,
    shells: [['desertsnail', 92, 0], ['turban', 74, 0], ['olive', 58, 3], ['murex', 36, 0], ['helmet', 6, 0]],
    food: { surface: 12, buried: 20, shallow: 8 },
    critters: [{ count: 2, sizes: [5, 8], species: 'raven' }, { count: 2, sizes: [1, 7], species: 'antlion' }, { count: 3, sizes: [2, 8], species: 'skink' }, { count: 2, sizes: [1, 6], species: 'darkling' }],
    birds: [{ count: 1, size: 6 }, { count: 1, size: 7 }],
  },
  {
    ...DUNE,
    id: 'the-great-dune', name: 'The Great Dune', seed: 210, width: 124, height: 44, parTime: 820,
    hint: 'Every shell of the Dune Sea, from the desert snail to the helmet on top of the Great Dune.',
    profile: [[0, 9], [10, 9], [32, 18], [70, 20], [96, 22], [123, 23]],
    pits: [[52, 3], [84, 4], [108, 3]],
    rocks: [[60, 34, 3], [100, 36, 3.5]],
    startCol: 116,
    shells: [['desertsnail', 102, 0], ['turban', 90, 0], ['nerite', 76, 0], ['olive', 64, 4], ['murex', 44, 0], ['helmet', 5, 0]],
    food: { surface: 14, buried: 24, shallow: 8 },
    critters: [{ count: 2, sizes: [5, 8], species: 'raven' }, { count: 3, sizes: [1, 7], species: 'antlion' }, { count: 3, sizes: [2, 8], species: 'skink' }, { count: 3, sizes: [1, 6], species: 'darkling' }],
    birds: [{ count: 2, size: 7 }],
  },
];
