import type { LevelDef } from './types';

/**
 * Beach 5, Ash & Basalt: black volcanic sand under a smoking volcano, with
 * basalt columns standing out of it (see docs/inkcrab-levels.md). Its idea
 * is steam: vents in the rock hiss, then blow, throwing whatever stands
 * over them high into the air. That's the way up onto the columns, where
 * the shells are; it tosses hunters and food too, and sand dropped into a
 * vent plugs it. Sally Lightfoot crabs hop up the rock after you; a
 * Galápagos hawk hunts from the sky. Small prey: lava lizards.
 */
const BASALT: Pick<LevelDef, 'fry' | 'ground'> = { fry: 'lavalizard', ground: 'black' };

export const BEACH_5: readonly LevelDef[] = [
  {
    ...BASALT,
    id: 'black-sand', name: 'Black Sand', seed: 501, width: 64, height: 32, parTime: 150,
    hint: 'A steam vent hisses, then blows. Stand over it and it throws you high: steer onto the basalt column, where the horn shell is.',
    profile: [[0, 17], [63, 19]],
    columns: [[30, 4, 6]],
    vents: [[27, 9, 6, 0]],
    startCol: 6,
    shells: [['drupe', 16, 0], ['hornshell', 32, 0]],
    food: { surface: 12, buried: 8, shallow: 5 },
    critters: [{ count: 2, sizes: [1, 2], species: 'lavalizard' }],
    teach: ['vent'],
  },
  {
    ...BASALT,
    id: 'organ-pipes', name: 'Organ Pipes', seed: 502, width: 72, height: 34, parTime: 200,
    hint: 'Columns of basalt like organ pipes. Each vent throws you as high as it can: the tall one reaches the spindle shell.',
    profile: [[0, 19], [71, 21]],
    columns: [[23, 3, 5], [43, 4, 9]],
    vents: [[20, 8, 6, 0], [40, 12, 7, 3]],
    startCol: 6,
    shells: [['drupe', 12, 0], ['hornshell', 24, 0], ['spindle', 45, 0]],
    food: { surface: 13, buried: 12, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'lavalizard' }],
  },
  {
    ...BASALT,
    id: 'sally-lightfoot', name: 'Sally Lightfoot', seed: 503, width: 76, height: 34, parTime: 250,
    hint: 'Young Sally Lightfoot crabs run and hop up the rocks. Inked red, they can catch you: hide in your shell, or let a vent throw you up out of reach.',
    profile: [[0, 19], [75, 21]],
    columns: [[30, 3, 6], [56, 4, 8]],
    vents: [[27, 9, 6, 0], [53, 11, 6, 3]],
    startCol: 6,
    shells: [['drupe', 14, 0], ['hornshell', 31, 0], ['spindle', 58, 0]],
    food: { surface: 13, buried: 13, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 2], species: 'sallycrab' }, { count: 1, sizes: [5, 5], species: 'sallycrab' }, { count: 2, sizes: [1, 3], species: 'lavalizard' }],
    teach: ['hide'],
  },
  {
    ...BASALT,
    id: 'under-the-ash', name: 'Under the Ash', seed: 504, width: 76, height: 36, parTime: 300,
    hint: 'A spindle shell lies buried in the black sand. Dig down to it; and if a vent is in the way, plug it with sand.',
    profile: [[0, 19], [75, 21]],
    columns: [[24, 3, 6]],
    vents: [[21, 9, 6, 0], [48, 8, 7, 2]],
    startCol: 6,
    shells: [['drupe', 12, 0], ['hornshell', 25, 0], ['spindle', 52, 4]],
    food: { surface: 13, buried: 15, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'sallycrab' }, { count: 1, sizes: [5, 5], species: 'sallycrab' }, { count: 2, sizes: [1, 4], species: 'lavalizard' }],
    teach: ['buried'],
  },
  {
    ...BASALT,
    id: 'vent-field', name: 'Vent Field', seed: 505, width: 92, height: 36, parTime: 380,
    hint: 'A field of vents across the lava. Ride them from column to column; the bonnet waits on the last one.',
    profile: [[0, 20], [91, 22]],
    columns: [[22, 3, 5], [40, 3, 7], [60, 3, 9], [80, 4, 10]],
    vents: [[19, 8, 6, 0], [37, 10, 6, 2], [57, 12, 6, 4], [77, 13, 7, 1]],
    startCol: 6,
    shells: [['drupe', 12, 0], ['hornshell', 23, 0], ['spindle', 41, 0], ['bonnet', 82, 0]],
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'sallycrab' }, { count: 1, sizes: [6, 6], species: 'sallycrab' }, { count: 3, sizes: [1, 4], species: 'lavalizard' }],
  },
  {
    ...BASALT,
    id: 'hawk-island', name: 'Hawk Island', seed: 506, width: 88, height: 36, parTime: 420,
    hint: 'A Galápagos hawk hunts over the black sand. When its red shadow tightens on you, dig in under the sand or hide in your shell.',
    profile: [[0, 20], [87, 22]],
    columns: [[30, 3, 6], [62, 4, 8]],
    vents: [[27, 9, 6, 0], [59, 11, 7, 3]],
    startCol: 6,
    shells: [['drupe', 14, 0], ['hornshell', 31, 0], ['spindle', 46, 0], ['bonnet', 64, 0]],
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'sallycrab' }, { count: 3, sizes: [1, 4], species: 'lavalizard' }],
    birds: [{ count: 1, size: 6, species: 'hawk' }],
    teach: ['sky'],
  },
  {
    ...BASALT,
    id: 'fumarole-ridge', name: 'Fumarole Ridge', seed: 507, width: 96, height: 38, parTime: 500,
    hint: 'A ridge of fumaroles under the volcano: vents, Sally Lightfoots and the hawk. The bonnet is on the high column.',
    profile: [[0, 21], [30, 22], [60, 20], [95, 23]],
    columns: [[20, 3, 5], [46, 3, 8], [72, 4, 11]],
    vents: [[17, 8, 6, 0], [43, 11, 6, 3], [69, 14, 7, 1]],
    startCol: 6,
    shells: [['drupe', 12, 0], ['hornshell', 21, 0], ['spindle', 47, 0], ['bonnet', 74, 0]],
    food: { surface: 15, buried: 18, shallow: 8 },
    critters: [{ count: 2, sizes: [1, 5], species: 'sallycrab' }, { count: 1, sizes: [6, 6], species: 'sallycrab' }, { count: 3, sizes: [1, 5], species: 'lavalizard' }],
    birds: [{ count: 1, size: 6, species: 'hawk' }],
  },
  {
    ...BASALT,
    id: 'lava-tubes', name: 'Lava Tubes', seed: 508, width: 96, height: 38, parTime: 560,
    hint: 'Boulders of old lava, and the bonnet buried among them. Dig for it; the vents will carry you over the rocks.',
    profile: [[0, 20], [95, 23]],
    columns: [[26, 3, 6], [70, 3, 7]],
    rocks: [[44, 21, 2.2], [54, 22, 2.6]],
    vents: [[23, 9, 6, 0], [40, 8, 6, 2], [67, 10, 7, 4]],
    startCol: 6,
    shells: [['drupe', 12, 0], ['hornshell', 27, 0], ['spindle', 71, 0], ['bonnet', 49, 4]],
    food: { surface: 15, buried: 20, shallow: 8 },
    critters: [{ count: 2, sizes: [2, 5], species: 'sallycrab' }, { count: 1, sizes: [6, 6], species: 'sallycrab' }, { count: 3, sizes: [1, 5], species: 'lavalizard' }],
    birds: [{ count: 1, size: 6, species: 'hawk' }],
  },
  {
    ...BASALT,
    id: 'eruption', name: 'Eruption', seed: 509, width: 104, height: 40, parTime: 680,
    hint: 'The volcano is restless: the vents blow fast and high. The harp shell is on top of the tallest column.',
    profile: [[0, 22], [103, 25]],
    columns: [[20, 3, 5], [40, 3, 8], [62, 3, 10], [84, 4, 13]],
    vents: [[17, 8, 4.5, 0], [37, 11, 4.5, 1.5], [59, 13, 5, 3], [81, 16, 5, 0.5]],
    startCol: 6,
    shells: [['drupe', 12, 0], ['hornshell', 21, 0], ['spindle', 41, 0], ['bonnet', 63, 0], ['harp', 86, 0]],
    food: { surface: 16, buried: 22, shallow: 9 },
    critters: [{ count: 2, sizes: [2, 6], species: 'sallycrab' }, { count: 1, sizes: [7, 7], species: 'sallycrab' }, { count: 3, sizes: [1, 5], species: 'lavalizard' }],
    birds: [{ count: 1, size: 7, species: 'hawk' }],
  },
  {
    ...BASALT,
    id: 'the-summit-vent', name: 'The Summit Vent', seed: 510, width: 120, height: 42, parTime: 980,
    hint: 'Every shell of the black beach, from the drupe on the sand to the harp on the great column under the volcano.',
    profile: [[0, 22], [60, 24], [119, 26]],
    columns: [[22, 3, 5], [44, 3, 7], [66, 3, 9], [96, 5, 14]],
    rocks: [[80, 25, 2.4]],
    vents: [[19, 8, 6, 0], [41, 10, 6, 2], [63, 12, 6, 4], [93, 17, 6, 1]],
    startCol: 6,
    shells: [['drupe', 12, 0], ['hornshell', 23, 0], ['spindle', 45, 0], ['bonnet', 67, 0], ['harp', 98, 0]],
    food: { surface: 20, buried: 32, shallow: 13, start: 10 },
    critters: [{ count: 1, sizes: [2, 4], species: 'sallycrab' }, { count: 1, sizes: [6, 6], species: 'sallycrab' }, { count: 5, sizes: [1, 6], species: 'lavalizard' }],
    birds: [{ count: 1, size: 6, species: 'hawk' }],
  },
];
