import type { LevelDef } from './types';

/**
 * Beach 9, Frost Shingle: a pebble beach on the Labrador coast in early
 * spring, pack ice offshore (see docs/inkcrab-levels.md). Its idea is the
 * wind: gusts come and go on a steady rhythm, shoving a crab in a light
 * shell along (furthest in the air and on ice), so heavy shells and the
 * lee of the shingle ridges and boulders count. Frozen pools are slippery
 * underfoot and can't be dug. In a gust no bird can hover, food blows into
 * the lee, and an Arctic fox smells you from far downwind but not upwind.
 * Snow crabs hunt by sight; a snowy owl hunts from the sky. Small prey:
 * sea spiders.
 */
const FROST: Pick<LevelDef, 'fry' | 'ground'> = { fry: 'seaspider', ground: 'shingle' };

export const BEACH_9: readonly LevelDef[] = [
  {
    ...FROST,
    id: 'shingle-shore', name: 'Shingle Shore', seed: 901, width: 64, height: 32, parTime: 150,
    hint: 'A frozen pool lies across the shingle. On ice you slide, so mind where you stop: drop sand on it to get a grip.',
    profile: [[0, 18], [63, 20]],
    startCol: 6,
    ice: [[22, 10, 2]],
    shells: [['wentletrap', 3, 14, 0], ['arcticmoon', 4, 40, 0]],
    food: { surface: 13, buried: 9, shallow: 5 },
    teach: ['ice'],
  },
  {
    ...FROST,
    id: 'first-gust', name: 'First Gust', seed: 902, width: 72, height: 34, parTime: 200,
    hint: 'Here comes the wind. A gust blows a light shell along, most in the air: shelter behind a rock, or jump with it behind you. A Neptune whelk lies up on the ridge.',
    profile: [[0, 19], [43, 20], [45, 15], [52, 15], [54, 20], [71, 21]],
    rocks: [[28, 20, 1.8]],
    startCol: 6,
    shells: [['wentletrap', 3, 14, 0], ['arcticmoon', 4, 33, 0], ['neptunewhelk', 5, 48, 0], ['neptunewhelk', 6, 62, 0]],
    wind: { period: 30, gust: 8, offset: 12 },
    food: { surface: 13, buried: 12, shallow: 6 },
    teach: ['wind'],
  },
  {
    ...FROST,
    id: 'snow-crabs', name: 'Snow Crabs', seed: 903, width: 76, height: 34, parTime: 250,
    hint: 'Snow crabs hunt by sight, and they\'re quick on the pebbles. Inked red, they can catch you: hide in your shell, where the wind can\'t move you.',
    profile: [[0, 19], [75, 21]],
    rocks: [[34, 20, 1.8], [58, 21, 2]],
    startCol: 6,
    shells: [['wentletrap', 3, 12, 0], ['arcticmoon', 4, 28, 0], ['neptunewhelk', 5, 42, 0], ['neptunewhelk', 6, 64, 0]],
    wind: { period: 34, gust: 8, offset: 8, dir: -1 },
    food: { surface: 13, buried: 13, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'snowcrab' }, { count: 1, sizes: [5, 5], species: 'snowcrab' }],
    teach: ['hide'],
  },
  {
    ...FROST,
    id: 'under-the-ice', name: 'Under the Ice', seed: 904, width: 76, height: 36, parTime: 300,
    hint: 'A Neptune whelk lies buried under a frozen pool. Ice can\'t be dug: dig in from the sand at its edge and tunnel underneath.',
    profile: [[0, 19], [75, 21]],
    rocks: [[30, 20, 1.8]],
    startCol: 6,
    ice: [[44, 12, 2]],
    shells: [['wentletrap', 3, 12, 0], ['arcticmoon', 4, 26, 0], ['neptunewhelk', 5, 37, 0], ['neptunewhelk', 6, 50, 5]],
    wind: { period: 36, gust: 8, offset: 6 },
    food: { surface: 13, buried: 15, shallow: 6 },
    critters: [{ count: 2, sizes: [1, 3], species: 'snowcrab' }, { count: 1, sizes: [5, 5], species: 'snowcrab' }],
    teach: ['buried'],
  },
  {
    ...FROST,
    id: 'storm-ridges', name: 'Storm Ridges', seed: 905, width: 92, height: 36, parTime: 380,
    hint: 'Storms have heaped the shingle into ridges, a shell beyond each. Shelter in their lee when it gusts: the Arctic whelk lies past the last.',
    profile: [[0, 20], [20, 20], [24, 17], [28, 20], [44, 21], [48, 18], [52, 21], [68, 22], [72, 19], [76, 22], [91, 22]],
    startCol: 6,
    shells: [['wentletrap', 3, 12, 0], ['arcticmoon', 4, 32, 0], ['neptunewhelk', 5, 40, 0], ['neptunewhelk', 6, 58, 0], ['arcticwhelk', 7, 82, 0]],
    wind: { period: 38, gust: 8, offset: 6 },
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'snowcrab' }, { count: 1, sizes: [5, 5], species: 'snowcrab' }],
  },
  {
    ...FROST,
    id: 'snowy-owl', name: 'Snowy Owl', seed: 906, width: 88, height: 36, parTime: 420,
    hint: 'A snowy owl hunts over the shingle. When its red shadow tightens on you, get under the sand or hide in your shell. It can\'t hover in a gust.',
    profile: [[0, 20], [87, 22]],
    rocks: [[26, 21, 1.8], [52, 21, 2.2]],
    startCol: 6,
    ice: [[64, 8, 2]],
    shells: [['wentletrap', 3, 14, 0], ['arcticmoon', 4, 30, 0], ['neptunewhelk', 5, 42, 0], ['neptunewhelk', 6, 56, 0], ['arcticwhelk', 7, 78, 0]],
    wind: { period: 36, gust: 9, offset: 4 },
    food: { surface: 14, buried: 16, shallow: 7 },
    critters: [{ count: 2, sizes: [1, 4], species: 'snowcrab' }],
    birds: [{ count: 1, size: 6, species: 'snowyowl' }],
    teach: ['sky'],
  },
  {
    ...FROST,
    id: 'arctic-fox', name: 'Arctic Fox', seed: 907, width: 96, height: 38, parTime: 500,
    hint: 'An Arctic fox noses along the strandline. It hunts by smell: in a gust it smells you from far downwind, but not at all upwind.',
    profile: [[0, 21], [40, 22], [95, 23]],
    rocks: [[36, 22, 2], [70, 23, 2]],
    startCol: 6,
    shells: [['wentletrap', 3, 12, 0], ['arcticmoon', 4, 26, 0], ['neptunewhelk', 5, 40, 0], ['neptunewhelk', 6, 50, 0], ['arcticwhelk', 7, 80, 0]],
    wind: { period: 34, gust: 9, offset: 2, dir: -1 },
    food: { surface: 15, buried: 18, shallow: 8, start: 6 },
    critters: [{ count: 1, sizes: [5, 5], species: 'arcticfox' }, { count: 2, sizes: [1, 3], species: 'snowcrab' }],
    teach: ['fox'],
  },
  {
    ...FROST,
    id: 'pack-ice', name: 'Pack Ice', seed: 908, width: 96, height: 38, parTime: 560,
    hint: 'Frozen pools, boulders, the wind and everyone out hunting. The Arctic whelk is buried among the rocks.',
    profile: [[0, 20], [95, 23]],
    rocks: [[46, 21, 2.2], [58, 22, 2.6]],
    startCol: 6,
    ice: [[18, 8, 2], [70, 12, 2]],
    shells: [['wentletrap', 3, 12, 0], ['arcticmoon', 4, 30, 0], ['neptunewhelk', 5, 36, 0], ['neptunewhelk', 6, 42, 0], ['arcticwhelk', 7, 52, 4]],
    wind: { period: 36, gust: 9, offset: 4 },
    food: { surface: 15, buried: 20, shallow: 8, start: 6 },
    critters: [{ count: 2, sizes: [2, 5], species: 'snowcrab' }, { count: 1, sizes: [4, 4], species: 'arcticfox' }],
    birds: [{ count: 1, size: 6, species: 'snowyowl' }],
  },
  {
    ...FROST,
    id: 'blizzard', name: 'Blizzard', seed: 909, width: 104, height: 40, parTime: 680,
    hint: 'A blizzard: long, hard gusts that turn about, and every hunter out. Get a heavy shell, keep to the lee, and climb to the Iceland whelk on the high ridge.',
    profile: [[0, 22], [80, 24], [84, 20], [94, 20], [98, 25], [103, 25]],
    rocks: [[30, 23, 2], [60, 24, 2.2]],
    startCol: 6,
    ice: [[40, 10, 2]],
    shells: [['wentletrap', 3, 12, 0], ['arcticmoon', 4, 26, 0], ['neptunewhelk', 5, 36, 0], ['neptunewhelk', 6, 54, 0], ['arcticwhelk', 7, 68, 0], ['icelandwhelk', 8, 90, 0]],
    wind: { period: 26, gust: 12, offset: 6, turns: true },
    food: { surface: 16, buried: 22, shallow: 9, start: 8 },
    critters: [{ count: 2, sizes: [2, 5], species: 'snowcrab' }, { count: 1, sizes: [6, 6], species: 'arcticfox' }],
    birds: [{ count: 1, size: 6, species: 'snowyowl' }],
  },
  {
    ...FROST,
    id: 'frost-shingle', name: 'Frost Shingle', seed: 910, width: 120, height: 42, parTime: 900,
    hint: 'Every shell of the shingle, from the wentletrap by the start to the Iceland whelk up on the last storm ridge.',
    profile: [[0, 22], [46, 24], [50, 21], [54, 24], [96, 26], [100, 21], [110, 21], [114, 26], [119, 26]],
    rocks: [[34, 23, 2], [78, 25, 2.4]],
    startCol: 6,
    ice: [[60, 12, 2], [86, 8, 2]],
    shells: [['wentletrap', 3, 12, 0], ['arcticmoon', 4, 28, 0], ['neptunewhelk', 5, 42, 0], ['neptunewhelk', 6, 56, 0], ['arcticwhelk', 7, 66, 5], ['icelandwhelk', 8, 105, 0]],
    wind: { period: 34, gust: 10, offset: 10, dir: -1, turns: true },
    food: { surface: 18, buried: 28, shallow: 11, start: 10 },
    critters: [{ count: 2, sizes: [2, 5], species: 'snowcrab' }, { count: 1, sizes: [6, 6], species: 'arcticfox' }],
    birds: [{ count: 1, size: 6, species: 'snowyowl' }],
  },
];
